### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [grgk/mqueue#2]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by grgk** [comment]
Hi,
Thanks for your feedback. I'd like to adapt some standards, but it looks I have to wait for some PSR related changes first, as described here: https://github.com/queue-interop/queue-interop/issues/9

**Comment by makasim** [comment]
@grgk I am going to get rid of `Psr` prefix in the next couple of month, for the upcoming version it would be a BC feature.
